matrix:

  include:
    language: python
    python:
        - "3.6"
    dist: trusty
    sudo: required
    env:
        - DJANGO_VERSION=1.11
        - TRAVIS=True
    install:
        - pip install -q Django=$DJANGO_VERSION
        - pip install -q -r requirements.txt
    script:
        - python manage.py makemigrations
        - python manage.py migrate
        - python -m pytest -n 3 --cov-config .coveragerc --cov=.

    - language: node_js
      node_js:
        - "8"
      dist: trusty
      sudo: required
      addons:
        chrome: stable
      cache:
        yarn: true
        directories:
          - node_modules
      install:
        - yarn
      script:
        - yarn mocha:all

notifications:
  email:
    - we.veggieavocado@gmail.com
    - ppark9553@gmail.com
  on_success: always
  on_failure: always
