version: '3'

services:
  nginx:
    container_name: soul_nginx
    build: ./soul_nginx
    links:
      - soul:soul
    ports:
      - 3000:3000
    depends_on:
      - soul

  soul:
    container_name: soul_server
    build: .
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=docker
    links:
      - mongo

  mongo:
    image: soul_mongo
    ports:
      - 27017:27017
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
    command: echo 'Data Container for MongoDB'
